# Site settings
description: A blog from Damian Flynn, a Microsoft MVP and Cisco Champion
baseurl: / # the subpath of your site, e.g. /blog/
url: http://blog.damianflynn.com
safe: False
title: Making Incredible Technology, Incredibly Simple
cover: assets/images/blog-cover.jpg
author: Damian Flynn
logo: assets/images/logos/sitelogo.svg
logo_dark: assets/images/logos/sitelogo.svg
favicon: assets/images/logos/favicon.png
#site_copyright: 2008-18 Damian Flynn.
site_url: https://blog.damianflynn.com/
#map_url: https://www.google.com/maps/place/Deer+Crest/@54.1205971,-9.240263,17z/data=!3m1!4b1!4m5!3m4!1s0x485938ff01b1f683:0xb699b4b3bca72fa0!8m2!3d54.1205971!4d-9.2380743


# Font Awesome version
fa_version: 4.6.0

# Build settings
timezone: Europe/Dublin
markdown: kramdown
highlighter: none #rouge
paginate: 100 # it will paginate after this number
language: 'en-uk'

# Permalinks
permalink: /:title/ 
# Authors' info in `_data/authors.yml`
#permalink: /author/:author 
# Tags' info in `_data/tags_info.yml`
#permalink: /tag/:tag

plugins_dir: [_plugins]
plugins: 
  - jekyll-paginate
  - jekyll-feed
#  - jekyll-mentions
#  - jekyll-redirect-from
#  - jekyll-seo-tag
  - jekyll-sitemap

CNAME: #add cname for website to be created

# Social info
navigation: True # show the navbar links
subscribers: False # you need to connect an external service for this to work,
twitter: damian_flynn # replace by your username
facebook: False # replace by your username
linkedin: damianflynn
github: damian_flynn

# Utteranc.es
comments: True
comments_identifier: DamianFlynn/damianflynn.github.io # replace with your id username

# Analytics
google_analytics: UA-64134408-1 # replace with your GA tracking identifier
application_insights: df18f8e9-8d8e-4506-b07b-7bcb088f74f5

# gems and other configs

feed:
  path: feed.xml

# or "master" otherwise
#lsi: False
#username: jekyller
#repo: jasper2
#branch: master
#relative_source: ../jasper2/
#destination: ../jasper2-pages/


exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
